folio-org/folio-spring-support

Jenkinsfile, README.md
=> FOLIO-722 initial repo setup

src/main/java/org/folio/spring/data/OffsetRequest.java
Add equals()/hashCode()//toString() to OffsetRequest
=> Add equals()/hashCode()/toString() to OffsetRequest

src/main/java/org/folio/spring/config/DefaultExceptionHandler.java
This change adds correct exception handling for DB exceptions related to constraint violation. It provides a correct error message, content type, and HTTP response code to the client.
An additional ExceptionHandler is added to the DefaultExceptionHandler
=> Correct handling for Constraint Violation exceptions

src/main/java/org/folio/spring/config/DataSourceSchemaAdvisorBeanPostProcessor.java
Fix spring data source adviser for proxy classes
=> Fix spring data source adviser for proxy classes

src/main/java/org/folio/spring/DefaultFolioExecutionContext.java, src/main/java/org/folio/spring/FolioExecutionContext.java, src/main/java/org/folio/spring/scope/EmptyFolioExecutionContextHolder.java, src/main/java/org/folio/spring/utils/JWTokenUtils.java, src/test/java/org/folio/spring/DefaultFolioExecutionContextTest.java, src/test/java/org/folio/spring/utils/JWTokenUtilsTest.java
`DefaultFolioExecutionContext` should contains userId and userName.
If `x-okapi-token` header exists then parse token and fetch userId and userName.
=> FOLSPRINGB-14 Fetch userId and userName from x-okapi-token

lombok.config, pom.xml, src/main/java/org/folio/spring/data/OffsetRequest.java, src/test/java/org/folio/junit/extension/RandomInt.java, src/test/java/org/folio/junit/extension/RandomLong.java, src/test/java/org/folio/junit/extension/RandomParametersExtension.java, src/test/java/org/folio/spring/FolioExecutionContextTest.java, src/test/java/org/folio/spring/data/OffsetRequestTest.java, src/test/java/org/folio/spring/utils/RequestUtilsTest.java
Increase code coverage
* write tests
* add junit extension to init test parameters with randomly generated int/long values
=> FOLSPRINGB-16 Increase code coverage

README.md, doc/release-notes.md
=> FOLSPRINGB-26 Create v2.0.0 release notes

NEWS.md
=> FOLSPRINGB-27 Update NEWS

pom.xml, src/main/java/org/folio/spring/config/FolioSpringConfiguration.java
=> FOLSPRINGB-32 Upgrade to Spring v2.6.2

NEWS.md, doc/release-notes.md, pom.xml
=> Prepare to next dev iteration

src/main/java/org/folio/spring/controller/TenantController.java, src/main/java/org/folio/spring/service/TenantService.java
=> FOLSPRINGB-38 Update tenants without check

pom.xml
=> FOLSPRINGB-48 Upgrade spring-boot to 2.6.6

pom.xml
Use PostgreSQL version provided by Spring Boot.
This pull request replaces #36.
=> FOLSPRINGB-36: Add postgres dependency to pom.xml

README.md, src/main/java/org/folio/spring/FolioExecutionContext.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java
Javadoc and readme section are added to inform developers about appropriate usage of FolioExecutionContext.
=> FOLIO-3448 Javadoc for FolioExecutionContext is added

NEWS.md, README.md, src/main/java/org/folio/spring/scope/FolioExecutionContextSetter.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, src/main/java/org/folio/spring/scope/filter/FolioExecutionScopeFilter.java, src/test/java/org/folio/spring/scope/FolioExecutionContextSetterTest.java
FolioExecutionContextSetter implementing AutoCloseable.
Reduce visibility of FolioExecutionScopeExecutionContextManager methods
to enforce usage of FolioExecutionContextSetter.
=> FOLSPRINGB-58: Async helper - FolioExecutionContextSetter

NEWS.md, pom.xml
Released tag: [v5.0.1](https://github.com/folio-org/folio-spring-base/tree/v5.0.1)
=> FOLSPRINGB-77: Release v5.0.1

src/main/java/org/folio/spring/FolioExecutionContext.java
=> FOLSPRINGB-81: typo in the java doc

NEWS.md, pom.xml
_Describe the purpose of the pull request. Include background information if necessary._
_How does this change fulfill the purpose?_
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._
=> Prepare for v6.1.0 development iteration

src/main/java/org/folio/spring/DefaultFolioExecutionContext.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java
DefaultFolioExecutionContext from message headers
=> DefaultFolioExecutionContext from message headers

src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, src/test/java/org/folio/spring/cql/JpaCqlRepositoryTest.java, src/test/java/org/folio/spring/cql/domain/Person.java, src/test/resources/insert-data.sql, src/test/resources/schema.sql
[FOLSPRINGB-99](https://issues.folio.org/browse/FOLSPRINGB-99) - Add support for filtering by date range in JpaCqlRepository
* Added support for LocalDateTime fields
* Updated unit tests
=> FOLSPRINGB-99 - Add support for filtering by date range in JpaCqlRepository

NEWS.md, pom.xml
- update NEWS.md
- prepare for next development iteration
=> Release v6.1.0

folio-spring-base/src/main/resources/log4j2-json.properties, folio-spring-base/src/main/resources/log4j2.properties
=> remove threshold filters

pom.xml
https://issues.folio.org/browse/FOLSPRINGB-123
=> FOLSPRINGB-123: Upgrade cql2pgjson Poppy RMB version 35.1.0

folio-spring-system-user/README.md, folio-spring-system-user/src/main/java/org/folio/spring/client/AuthnClient.java, folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/PrepareSystemUserServiceTest.java
_Describe the purpose of the pull request. Include background information if necessary._
The purpose of this PR is to make code changes as per the need of FOLSPRINGB-127.
_How does this change fulfill the purpose?_
If the user is existing and the system user password has been specified in the environment variables then, the existing users credentials should be deleted and the credentials should be recreated as per the username, password specified in environment variables.
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._
=> FOLSPRINGB-127 - Update existing system-user credentials based on provided system user environment variable.

folio-spring-system-user/src/main/java/org/folio/spring/client/AuthnClient.java, folio-spring-system-user/src/main/java/org/folio/spring/client/PermissionsClient.java, folio-spring-system-user/src/main/java/org/folio/spring/client/UsersClient.java
The bug was created during the actualization of the POC branch. It should be fixed.
[MODROLESKC-24](https://issues.folio.org/browse/MODROLESKC-24)
- put the right annotation parameters
_Describe the research stage. Add links to blog posts, patterns, libraries or addons used to solve this problem._
=> FOLSPRINGB-128: fix feign clients issue

folio-spring-testing/pom.xml, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/EnableMinio.java, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/MinioContainerExtension.java, folio-spring-testing/src/test/java/org/folio/spring/testing/extension/impl/MinioContainerExtensionTest.java
add Minio extension for testing submodule
Create annotation and implementation of extension
=> FOLSPRINGS-148: add Minio extension for testing submodule

folio-spring-base/pom.xml, folio-spring-common/pom.xml, folio-spring-cql/pom.xml, folio-spring-i18n/pom.xml, folio-spring-system-user/pom.xml, folio-spring-testing/pom.xml, pom.xml
Set module version to 8.1.0-SNAPSHOT
=> Set module version to 8.1.0-SNAPSHOT

NEWS.md, folio-spring-base/pom.xml, folio-spring-common/pom.xml, folio-spring-cql/pom.xml, folio-spring-i18n/pom.xml, folio-spring-system-user/pom.xml, folio-spring-testing/pom.xml, pom.xml
Prepare 8.2.0 development iteration
=> Prepare 8.2.0 development iteration

NEWS.md, folio-spring-testing/README.md, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/PostgresContainerExtension.java
Implement TESTCONTAINERS_POSTGRES_IMAGE 
https://folio-org.atlassian.net/wiki/display/TC/DR-000037+-+TESTCONTAINERS_POSTGRES_IMAGE
=> FOLSPRINGS-152 Implement TESTCONTAINERS_POSTGRES_IMAGE

NEWS.md, folio-spring-i18n/README.md, folio-spring-i18n/pom.xml, folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationFileLanguageExtractionTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationFileModuleExtractionTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationMapTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationMatchQualityTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/service/TranslationServiceGetFilesTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/service/TranslationServiceResolutionTest.java
Make translation service accept multiple keys
- added new method
https://folio-org.atlassian.net/browse/FOLSPRINGS-160
=> feat(i18n): make translation service accept multiple keys

pom.xml
Bump up commons-lang3.version to 3.17.0
=> Bump up commons-lang3.version to 3.17.0

folio-spring-i18n/src/main/java/org/folio/spring/i18n/model/TranslationMap.java, folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationMapTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/service/TranslationServiceFormatTest.java
Forgot to expose these from #187
=> [FOLSPRINGS-169] Expose formatString i18n methods

NEWS.md, folio-spring-base/pom.xml, folio-spring-common/pom.xml, folio-spring-cql/pom.xml, folio-spring-i18n/pom.xml, folio-spring-system-user/pom.xml, folio-spring-testing/pom.xml, pom.xml
Prepare for 8.3 development iteration
=> Prepare for 8.3 development iteration

folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/KafkaContainerExtension.java, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/MinioContainerExtension.java, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/PostgresContainerExtension.java
Starting testcontainers with 3 attempts that could increase efficiency of integration tests.
=> fix(testing): starting testcontainers with 3 attempts

NEWS.md, folio-spring-base/pom.xml, folio-spring-common/pom.xml, folio-spring-cql/pom.xml, folio-spring-i18n/pom.xml, folio-spring-system-user/pom.xml, folio-spring-testing/pom.xml, pom.xml
Prepare for next development iteration 9.1.0
=> Prepare for next development iteration 9.1.0

folio-spring-base/pom.xml, folio-spring-common/pom.xml, folio-spring-cql/pom.xml, folio-spring-i18n/pom.xml, folio-spring-system-user/pom.xml, folio-spring-testing/pom.xml, pom.xml
prepare for next development iteration 10.0.0
=> chore: prepare for next development iteration v10.0.0

NEWS.md, folio-spring-system-user/src/main/java/org/folio/spring/context/ExecutionContextBuilder.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserScopedExecutionService.java, folio-spring-system-user/src/test/java/org/folio/spring/context/ExecutionContextBuilderTest.java, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/SystemUserScopedExecutionServiceTest.java
Add headers parameter to executeSystemUserScoped method
[FOLSPRINGS-195](https://folio-org.atlassian.net/browse/FOLSPRINGS-195)
- Extend ExecutionContextBuilder with a method accepting headers
- Extend SystemUserScopedExecutionService with a method accepting headers
=> feat(system-user): Add headers parameter to executeSystemUserScoped method

NEWS.md, folio-spring-base/src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java
Change warning log to debug for execution scope not set up message
https://folio-org.atlassian.net/browse/FOLSPRINGS-202
=> FOLSPRINGS-202 change warning log to debug for execution scope not set up message
