pom.xml
Make use of Spring boot lo4j2 dependency instead of listing log4j2 libs explicitly. Exclude Spring boot default logging
=> Spring boot lo4j2 dependency

src/main/java/org/folio/spring/service/TenantService.java
Fix UnsatisfiedDependencyException: Error creating bean with name ‘tenantService’
Current approach of removing database support in module is:
1. Creating bean `folioTenantController` that implements `TenantApi`
2. Add properties to `application.properties`:
```
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration, org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration, org.springframework.boot.autoconfigure.jdbc.DataSourceTransactionManagerAutoConfiguration
spring.liquibase.enabled=false
```
`@Lazy` annotation on `TenantService` is needed to tell Spring to create this bean only if it is needed by default implementation of `TenantApi`
=> FOLSPRINGB-11 Fix issue with unsatisfied dependency

src/main/java/org/folio/spring/FolioExecutionContext.java, src/test/java/org/folio/spring/FolioExecutionContextTest.java
Remove deprecated method getUserName() from FolioExecutionContext
=> FOLSPRINGB-21 Remove deprecated method getUserName()

README.md, src/main/java/org/folio/spring/DefaultFolioExecutionContext.java, src/main/java/org/folio/spring/FolioExecutionContext.java, src/main/java/org/folio/spring/config/FeignClientConfiguration.java, src/main/java/org/folio/spring/filter/LoggingRequestFilter.java, src/main/java/org/folio/spring/filter/TenantOkapiHeaderValidationFilter.java, src/main/java/org/folio/spring/logging/FolioLoggingContextHolder.java, src/main/java/org/folio/spring/logging/FolioLoggingContextLookup.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, src/main/java/org/folio/spring/scope/filter/FolioExecutionScopeFilter.java, src/main/java/org/folio/spring/utils/MultiReadHttpServletRequestWrapper.java, src/main/resources/log4j2-json.properties, src/main/resources/log4j2.properties, src/test/java/org/folio/spring/DefaultFolioExecutionContextTest.java, src/test/java/org/folio/spring/FolioExecutionContextTest.java, src/test/java/org/folio/spring/config/FeignInfoLoggerTest.java, src/test/java/org/folio/spring/filter/LoggingRequestFilterTest.java, src/test/java/org/folio/spring/filter/appender/TestAppender.java, src/test/java/org/folio/spring/logging/FolioLoggingContextLookupTest.java, src/test/resources/log4j2-test.xml
* Include default log4j config that's aligned with the FOLIO logging format (https://wiki.folio.org/pages/viewpage.action?pageId=36576312)
* Log requests to module and responses from it
* Log requests to other modules with feign clients.
* Have an ability to enable/disable the logging from application properties
* Have an ability to specify how detailed log should be:
- log only request and response status
- log all above and headers of a request
- log all above and body of request/response
=> FOLSPRINGB-21 Setup default logging

pom.xml, src/main/java/org/folio/spring/cql/JpaCqlRepositoryImpl.java, src/main/java/org/folio/spring/data/OffsetRequest.java, src/main/java/org/folio/spring/liquibase/FolioPostgresDatabase.java, src/main/java/org/folio/spring/liquibase/FolioSpringLiquibase.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, src/test/java/org/folio/spring/data/OffsetRequestTest.java, src/test/java/org/folio/spring/liquibase/FolioPostgresDatabaseTest.java
Upgrade Spring Boot to v2.5.2
For testing purposes, mod-quick-marc and mod-tags were upgraded to this version of folio-spring-base. No issues were found after the upgrade. 
Release notes on how to upgrade to the new version of folio-spring-base will be provided with release.
A new version of Liquibase that comes with upgraded Spring Boot causes the issue when the migration script doesn't see database functions created in the public scheme.  
The root cause of that is setting PostgreSQL search_path to module scheme after each successful or not changeset execution. This search_path change executes in `liquibase.database.core.PostgresDatabase#rollback()` method.  
To fix this `FolioPostgresDatabase` class provided. It overrides this behavior. To make this class work instead of the default it …
=> FOLSPRINGB-25 Upgrade Spring Boot to v2.5.2

pom.xml
Fix log4j2 `RCE` vulnerability
- log4j2 version set to 2.16.0
[FOLSPRINGB-29](https://issues.folio.org/browse/FOLSPRINGB-29)
[CVE-2021-44228](https://github.com/advisories/GHSA-jfh8-c2jp-5v3q)
[CVE-2021-45046](https://github.com/advisories/GHSA-7rjr-3q55-vv33)
`mvn dependency:list | grep log4j` can be used to check log4j versions used
=> FOLSPRINGB-29 Kiwi R3 2021 - Log4j vulnerability verification and correction

pom.xml
Update Spring Boot from 2.6.2 to 2.6.3.
This indirectly updates log4j-core from 2.17.0 to 2.17.1 fixing a remote code execution vulnerability: https://nvd.nist.gov/vuln/detail/CVE-2021-44832
=> FOLSPRINGB-42: Spring Boot 2.6.3, log4j-core 2.17.1 (CVE-2021-44832)

pom.xml
Update Spring Boot from 2.6.6 to 2.6.7.
This indirectly updates spring-boot-starter-data-jpa from 2.6.6 to 2.6.7. This indirectly updates org.springframework:spring-context from 5.3.18 to 5.3.19 fixing Improper Handling of Case Sensitivity: https://nvd.nist.gov/vuln/detail/CVE-2022-22968
Update Liquibase from 4.5.0 to 4.9.1 fixing XML External Entity (XXE) Injection: https://nvd.nist.gov/vuln/detail/CVE-2022-0839
=> FOLSPRINGB-51: Spring Boot 2.6.7, Liquibase 4.9.1 (CVE-2022-0839)

NEWS.md, pom.xml
* [FOLSPRINGB-36](https://issues.folio.org/browse/FOLSPRINGB-36): Add postgres runtime dependency to pom.xml
* [FOLSPRINGB-51](https://issues.folio.org/browse/FOLSPRINGB-51): Spring Boot 2.6.7 (CVE-2022-22968), Liquibase 4.9.1 (CVE-2022-0839)
=> Release 3.0.3

pom.xml
Migrate to Spring Boot 2.7.x.
https://spring.io/projects/spring-boot#support :
Open Source Support for Spring Boot 2.6.x ends 2022-11-24.
Open Source Support for Spring Boot 2.7.x ends 2023-05-18.
Morning Glory R2 2022 public release will be on 2022-08-08.
Nolana R3 2022 public release will be around 2022-12.
Orchid R1 2023 public release will be around 2023-04.
The support period for Morning Glory ends some time (to be determined) after Nolana public release date.
Therefore Spring Boot 2.6.x cannot be used for Morning Glory because Spring Boot support ends during the support period of Morning Glory.
For Morning Glory Spring Boot 2.7.x needs to be used so that we get security fixes during the complete support period.
=> FOLSPRINGB-52: Spring Boot 2.7.x for Morning Glory R2 2022

pom.xml
Upgrade spring-security-rsa from 1.0.10.RELEASE to 1.0.11.RELEASE. This indirectly upgrades org.bouncycastle:bcprov-jdk15on from 1.68 to 1.69 fixing weak cryptography in HMAC: https://app.snyk.io/vuln/SNYK-JAVA-ORGBOUNCYCASTLE-2841508
Upgrade org.postgresql:postgresql from 42.3.5  to 42.5.0 fixing SQL Injection: https://nvd.nist.gov/vuln/detail/CVE-2022-31197
While it is more unlikely than likely that any folio-spring-base using module is affected by these issues it is more easy for each module to bump the folio-spring-base version than investigate whether it is affected by the issues.
=> FOLSPRINGB-68: Upgrade spring-security-rsa, bcprov-jdk15on, postgresql

pom.xml
Upgrade org.yaml:snakeyaml from 1.30 to 1.31 fixing these issues:
* Denial of Service (DoS) https://nvd.nist.gov/vuln/detail/CVE-2022-25857
* Stack-based Buffer Overflow https://nvd.nist.gov/vuln/detail/CVE-2022-38749
* Stack-based Buffer Overflow https://nvd.nist.gov/vuln/detail/CVE-2022-38750
* Stack-based Buffer Overflow https://nvd.nist.gov/vuln/detail/CVE-2022-38751
* Stack-based Buffer Overflow https://nvd.nist.gov/vuln/detail/CVE-2022-38752
Upgrade lombok from 1.18.16 to 1.18.24 allowing a build with JDK 17.
Upgrade spring-boot-starter-parent from 2.7.0 to 2.7.3.
Upgrade spring-cloud-starter-openfeign from 3.1.2 to 3.1.4. This indirectly upgrades spring-security-rsa to 1.0.11.RELEASE making an explicit dependency entry for spring-security-rsa obsolete.
=> FOLSPRINGB-70: snakeyaml security fix, Lombok, Spring

src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, src/test/java/org/folio/spring/cql/JpaCqlRepositoryTest.java
As described in [FOLSPRINGB-72](https://issues.folio.org/browse/FOLSPRINGB-72), pagination does not work as expected when limit size is less than page size. The bug should be fixed.
- Cleared fetches if any: needless for the count query and it is even more efficient to get rid of them.
- Added more unit tests to cover business logic
=> FOLSPRINGB-72 - Count Criteria Query does not work as expected

pom.xml
Upgrade snakeyaml from 1.31 to 1.33 fixing Denial of Service attacks (DoS) caused by Stack-based Buffer Overflow:
https://nvd.nist.gov/vuln/detail/CVE-2022-38752
=> FOLSPRINGB-75: snakeyaml 1.33 fixing Stack Overflow CVE-2022-38752

pom.xml
Upgrade jackson-databind from 2.13.3 to 2.13.4.2 fixing Denial of Service (DoS) vulnerabilities:
https://nvd.nist.gov/vuln/detail/CVE-2022-42003
https://nvd.nist.gov/vuln/detail/CVE-2022-42004
Upgrade commons-text from 1.9 to 1.10.0 fixing Arbitrary Code Execution
https://nvd.nist.gov/vuln/detail/CVE-2022-42889
Upgrade RMB from 33.2.4 to 35.0.1.
Note that org.folio:cql2pgjson is a component of RMB:
https://github.com/folio-org/raml-module-builder/tree/v35.0.1
=> FOLSPRINGB-78: RMB 35.0.1, commons-text 1.10.0 fixing vulns

src/main/java/org/folio/spring/DefaultFolioExecutionContext.java, src/main/java/org/folio/spring/FolioExecutionContext.java, src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, src/test/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManagerTest.java
There is no common solution for cases when an asynchronous task should be executed using a particular FolioExecutionContext instance. This PR provides the implementation for such cases.
The approach is to wrap a runnable instance and set up the context right before executing Runnable.run(); and clear the context right after the execution.
N/A
N/A
=> Support for async execution with FolioExecutionContext

src/main/java/org/folio/spring/service/TenantService.java
Enabling two tenants in parallel fails. The error occurs due to schema-naming confusion. FolioSpringLiquibase class contains the "defaultSchemaName" used to apply SQL scripts. FolioSpringLiquibase is a singleton bean. It can't be instantiated as a prototype bean because it relies on the liquibase.Scope class that provides singleton implementation of the scope manager (SingletonScopeManager). Two simultaneously running DB updates just mesh the Scope.
Make the method createOrUpdateTenant synchronized
=> FOLSPRINGB-86: bugfix for version 6.0

src/main/java/org/folio/spring/service/TenantService.java
Enabling two tenants in parallel fails. The error occurs due to schema-naming confusion. FolioSpringLiquibase class contains the "defaultSchemaName" used to apply SQL scripts. FolioSpringLiquibase is a singleton bean. It can't be instantiated as a prototype bean because it relies on the liquibase.Scope class that provides singleton implementation of the scope manager (SingletonScopeManager). Two simultaneously running DB updates just mesh the Scope.
Make the method createOrUpdateTenant synchronized
=> FOLSPRINGB-86: bugfix for version 5.1

src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java
Because of the shared CqlParser instance, a race condition can occur when processing CQL statements by the JpaCqlRepositoryImpl.
Instantiate a new instance for every CQL parsing operation
=> Fix issue with the race condition with CqlParser shared object

src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java
non-public beginFolioExecutionContext avoids wrong tenant/user
Make methods package private
=> FOLSPRINGB-95 non-public beginFolioExecutionContext avoids wrong tenant/user

README.md, folio-spring-base/src/main/java/org/folio/spring/logging/FolioLoggingContextHolder.java, folio-spring-base/src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, folio-spring-base/src/test/java/org/folio/spring/logging/FolioLoggingContextLookupTest.java, folio-spring-base/src/test/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManagerTest.java
It is required to support the temporary switching of FolioExecutionContext and restore the previous context when the temporary context is finished.
Use a stack to store and restore the previous context
=> FOLSPRINGB-106 implementation for store/restore of FolioExecutionContext

.github/workflows/api-doc.yml, .github/workflows/api-lint.yml, .github/workflows/api-schema-lint.yml, Jenkinsfile, README.md, folio-spring-base/src/main/resources/swagger.api/tenant.yaml
[FOLIO-3678](https://issues.folio.org/browse/FOLIO-3678)
Use GitHub Workflows for [api-lint](https://dev.folio.org/guides/api-lint/) and [api-schema-lint](https://dev.folio.org/guides/describe-schema/) and [api-doc](https://dev.folio.org/guides/api-doc/)
(instead of Jenkins-operated CI stages).
=> FOLIO-3678 FOLSPRINGB-109 Use GitHub Workflows api-lint and api-schema-lint and api-doc

pom.xml
Upgrade Spring Boot from 3.1.0 to 3.1.1 fixing Information Exposure:
https://security.snyk.io/vuln/SNYK-JAVA-ORGAPACHETOMCATEMBED-5726234
=> FOLSPRINGB-111: Spring Boot 3.1.1 fixing CVE-2023-34981

folio-spring-base/src/main/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManager.java, folio-spring-base/src/test/java/org/folio/spring/scope/FolioExecutionScopeExecutionContextManagerTest.java
The goal is to fix the implementation of deque management for FolioContext. The current implementation has a defect in the propagation of the InheritableThreadLocal to the child thread. As a result both parent and child threads shared the same deque.
Override the childValue method in the NamedInheritableThreadLocal
=> Create a new deque for every Thread

folio-spring-cql/src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, folio-spring-cql/src/test/java/org/folio/spring/cql/JpaCqlRepositoryIT.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/Person.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/PersonCustomRepository.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/PersonCustomRepositoryImpl.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/PersonRepository.java, folio-spring-cql/src/test/resources/sql/jpa-cql-general-it-schema.sql, folio-spring-cql/src/test/resources/sql/jpa-cql-general-test-data.sql, folio-spring-cql/src/test/resources/sql/jpa-cql-person-test-data.sql
_In order to have more complex cql criteria queries we need to have possibility to extend the conditions for these queries in a flexible manner._
_Add JPA Specification support_
[_FOLSPRINGB-117_](https://issues.folio.org/browse/FOLSPRINGB-117)
Specific use case of one such query can be found in the following [PR](https://github.com/folio-org/mod-entities-links/pull/136/files#diff-562ae46213cadf3444fb756a3882131a1ec13bf10c8d04bfaaf6e1f383caceed)
=> FOLSPRINGB-117: Extend Cql to JPA Criteria with support to JPA Specification

folio-spring-system-user/pom.xml, folio-spring-system-user/src/main/java/org/folio/spring/config/SystemUserConfig.java, folio-spring-system-user/src/main/java/org/folio/spring/config/properties/SystemUserConfig.java, folio-spring-system-user/src/main/java/org/folio/spring/model/ResultList.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserService.java, folio-spring-system-user/src/main/resources/META-INF/spring/org.springframework.boot.autoconfigure.AutoConfiguration.imports, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/SystemUserServiceTest.java
_[FOLSPRINGB-118](https://issues.folio.org/browse/FOLSPRINGB-118) : Implement refresh token rotation method for edge module_
method overloading of authSystemUser(), getTokenWithExpiry(), getTokenLegacy() by supplying tenantId, username, and password as arguments, which can be utilized into the edge-module which has a mechanism of retrieving password from the salt, unlike other mod-* modules which retrieves it from the module's properties file.
=> FOLSPRINGB-118: Implement refresh token rotation method for edge module

folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserService.java
[FOLSPRINGB-119](https://issues.folio.org/browse/FOLSPRINGB-119) : Token retrieved from cache can expire during the time it is used in a request
_In folio-spring-system-user when we retrieve the token from the cache, we first check to see if it is expired. However, the request will take some unknown amount of time. It would be rare but possible that the token could expire during the time after which it was retrieved and used in the actual request. Adding a buffer should be sufficient to solve this._
_While comparing the cached token's expiration time with the current time, we compare it with the current time minus 30 seconds_
=> FOLSPRINGB-119 : Token retrieved from cache can expire during the time it is used in a request

folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserProperties.java, folio-spring-system-user/src/test/java/org/folio/spring/service/SystemUserPropertiesTest.java
The folio-spring-system-user library should reject an empty or null system user password.
Use case:
As a sysop I may accidentially forget to set the environment variable.
For example forgetting to add SYSTEM_USER_PASSWORD, or forget to add the secret to a deployment in Rancher, or having a typo in the variable name like SYSTEM_USERS_PASSWORD.
When the system user password is not set or is empty the attempt to create the system user when enabling the module for a tenant (or upgrading the module for a tenant) should fail with an error message about the missing password.
The module MUST NOT set an empty password.
This is security by default and is required for GDPR compliance (GDPR Article 25 "Data protection by design and by default").
Therefore folio-spring-system-user MUST reject a system …
=> FOLSPRINGB-126: Reject empty and null system user password

pom.xml
https://issues.folio.org/browse/FOLSPRINGB-130
Upgrade Spring Boot from 3.1.1 to 3.1.5. This indirectly upgrades tomcat-embed-core from 10.1.8 to 10.1.15 fixing Denial of Service (DoS), Access Restriction Bypass, Improper Input Validation, Incomplete Cleanup:
https://nvd.nist.gov/vuln/detail/CVE-2023-44487
https://nvd.nist.gov/vuln/detail/CVE-2023-41080
https://nvd.nist.gov/vuln/detail/CVE-2023-45648
https://nvd.nist.gov/vuln/detail/CVE-2023-42795
Upgrade spring-cloud-starter-openfeign from 4.0.3 to 4.0.4.
The spring-cloud-starter-openfeign upgrade indirectly upgrades commons-fileupload from 1.4 to 1.5 fixing Denial of Service (DoS):
https://nvd.nist.gov/vuln/detail/CVE-2023-24998
The spring-cloud-starter-openfeign upgrade indirectly removes the vulnerable dependency bcprov-jdk15on 1.69 …
=> FOLSPRINGB-130: Spring Boot 3.1.5, Spring Cloud Openfeign 4.0.4

folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserService.java, folio-spring-system-user/src/main/java/org/folio/spring/utils/TokenUtils.java, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/SystemUserServiceTest.java, folio-spring-system-user/src/test/java/org/folio/spring/utils/TokenUtilsTest.java
Fix "Invalid token" on system user operations
[FOLSPRINGB-132](https://issues.folio.org/browse/FOLSPRINGB-132)
Use half of access token expiration as user cache expiration
[RTR docs](https://wiki.folio.org/pages/viewpage.action?pageId=96414255) have a comment mentioning that new access token should be requested when half of ttl has passed
=> fix(refresh-token-rotation): Use half of access token expiration as user cache expiration

folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java, pom.xml
The attach-javadocs build phase fails:
https://jenkins-aws.indexdata.com/job/folio-org/job/folio-spring-support/job/master/27/execution/node/61/log/
```
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-javadoc-plugin:3.5.0:jar (attach-javadocs) on project folio-spring-i18n: MavenReportException: Error while generating Javadoc:
[ERROR] Exit code: 1
[ERROR] /home/jenkins/workspace/_org_folio-spring-support_master/folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java:38: error: cannot find symbol
[ERROR] @RequiredArgsConstructor(onConstructor_ = @Autowired)
[ERROR]                          ^
[ERROR]   symbol:   method onConstructor_()
[ERROR]   location: @interface RequiredArgsConstructor
```
As there is only one constructor Spring doesn't need …
=> FOLSPRINGB-137: javadoc cannot find symbol onConstructor_

folio-spring-i18n/src/main/java/org/folio/spring/i18n/model/TranslationFile.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationFileLanguageExtractionTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationFileModuleExtractionTest.java
The existing solution to extract module names from translation file paths would fail under certain conditions when run in JAR files.
This uses the more resilient resource description, as opposed to assuming a filename is present and able to be parsed.
In local testing, this description seemed to be the best option:
- `getFilename` only returns the last part (e.g. `en.json`) which is useless for this
- `getFile` assumes that a file exists, which may not be the case in JARs (our original error)
- `getURL` and `getURI` seem promising, however, we [originally tried this and it caused errors on Windows](https://github.com/folio-org/folio-spring-support/pull/122#pullrequestreview-1735346063) where Spring had trouble converting `C:\` into a legal URI that could then be decoded, since technically …
=> [FOLSPRINGB-138] Use more resilient method for translation module name extraction

folio-spring-cql/src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, folio-spring-cql/src/test/java/org/folio/spring/cql/JpaCqlRepositoryIT.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/Person.java, folio-spring-cql/src/test/resources/sql/jpa-cql-general-it-schema.sql, folio-spring-cql/src/test/resources/sql/jpa-cql-general-test-data.sql, folio-spring-cql/src/test/resources/sql/jpa-cql-person-test-data.sql
_Add possibility to specify fields in Cql query which are of Timestamp type._
Include Timestamp type to be checked when parsing cql query term from String.
Closes: [FOLSPRINGB-142](https://issues.folio.org/browse/FOLSPRINGB-142)
=> FOLSPRINGB-142: Add support for Timestamp type field in Cql query

folio-spring-base/src/main/java/org/folio/spring/client/EnrichUrlAndHeadersClient.java, folio-spring-base/src/test/java/org/folio/spring/client/EnrichUrlAndHeadersClientTest.java
Currently, we pass any `x-okapi` headers to other modules via feign clients, allowing sharing of token, user, and other request metadata.  We should also do this with the `Accept-Language` header, to ensure that any requests made also include this information, enabling downstream APIs to return locale-aware results.
This alters `EnrichUrlAndHeadersClient` to also check for and pass the `Accept-Language` header.  For ease of testing, the class has also been slightly refactored to extract some logic into static, easily-testable classes.
I see the code smell, and I have no clue how to address it — it seems to be a false positive that is not applicable in this case.
=> [FOLSPRINGB-139] Pass Accept-Language header in Feign clients

NEWS.md, folio-spring-cql/src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, folio-spring-cql/src/test/java/org/folio/spring/cql/JpaCqlRepositoryIT.java, folio-spring-cql/src/test/resources/sql/jpa-cql-person-test-data.sql
_Support filtering by undefined SQL DB Table attribute value._
_Specifically handle the case where attribute is defined with any value or undefined at all_
[FOLSPRINGS-144](https://folio-org.atlassian.net/browse/FOLSPRINGS-144)
=> FOLSPRINGB-144: Add support for Cql filtering by (un)defined attribute value

folio-spring-testing/pom.xml, pom.xml
Upgrade commons-compress from 1.24.0 to 1.26.1 fixing security vulnerabilities:
* https://nvd.nist.gov/vuln/detail/CVE-2024-25710 - Infinite loop
* https://nvd.nist.gov/vuln/detail/CVE-2024-26308 - Allocation of Resources Without Limits or Throttling
In addition unpin testcontainers version because the Spring Boot provided version overwrites the testcontainers provided version:
```
mvn dependency:tree -Dincludes=:commons-compress -Dverbose
[INFO] org.folio:folio-spring-testing:jar:8.2.0-SNAPSHOT
[INFO] \- org.testcontainers:testcontainers:jar:1.19.6:compile
[INFO]    \- org.apache.commons:commons-compress:jar:1.24.0:compile
[INFO] org.folio:folio-spring-cql:jar:8.2.0-SNAPSHOT
[INFO] \- org.folio:folio-spring-testing:jar:8.2.0-SNAPSHOT:test
[INFO]    \- …
```
=> FOLSPRINGS-153: commons-compress 1.26.1, unpin testcontainers, wiremock 3.4.2

.github/dependabot.yml, folio-spring-system-user/pom.xml, folio-spring-system-user/src/main/java/org/folio/spring/exception/SystemUserAuthorizationException.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserService.java, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/SystemUserServiceTest.java, pom.xml
edge-api-utils is adding unnecessary dependencies to the system-user submodule. This can lead to increased vulnerabilities in modules that use it.
Exclude edge-api-utils from system-user submodule
=> FOLSPRINGS-154 Exclude edge-api-utils from system-user submodule

NEWS.md, folio-spring-system-user/src/main/java/org/folio/spring/client/AuthnClient.java, folio-spring-system-user/src/test/java/org/folio/spring/systemuser/SystemUserServiceTest.java, folio-spring-system-user/src/test/java/org/folio/spring/utils/TokenUtilsTest.java
The `AuthnClient` which communicates with `mod-login` via [this endpoint](https://s3.amazonaws.com/foliodocs/api/mod-login/r/login.html#authn_login_with_expiry_post), however, the `folio-spring-system-user` library does not anticipate the full response, causing errors in certain modules where `fail-on-unknown-properties` is set to true (currently, only one module uses this, and that module had to disable that flag to use the library).
See https://folio-project.slack.com/archives/C01HUKJCMC7/p1716305138170359?thread_ts=1716301442.701229&cid=C01HUKJCMC7 for more details.
=> [FOLSPRINGS-157] Add missing property to LoginResponse in folio-spring-system-user

folio-spring-base/src/main/java/org/folio/spring/config/FolioSpringConfiguration.java
Optimize injection in the `DataSourceSchemaAdvisorBeanPostProcessor`
Remove warnings
```
WARN  PostProcessorChecker Bean 'org.folio.spring.config.FolioSpringConfiguration' of type [org.folio.spring.config.FolioSpringConfiguration$$SpringCGLIB$$0] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). The currently created BeanPostProcessor [dataSourceSchemaAdvisorBeanPostProcessor] is declared through a non-static factory method on that class; consider declaring it as static instead.
WARN  PostProcessorChecker Bean 'folioExecutionContext' of type [org.springframework.aop.scope.ScopedProxyFactoryBean] is not eligible for getting processed by all BeanPostProcessors (for example: not eligible for auto-proxying). Is this bean getting …
```
=> Fixed PostProcessorChecker Warnings

NEWS.md, folio-spring-testing/pom.xml, folio-spring-testing/src/main/java/org/folio/spring/testing/extension/impl/KafkaContainerExtension.java, folio-spring-testing/src/test/java/org/folio/spring/testing/extension/impl/KafkaContainerExtensionTest.java
Reverts folio-org/folio-spring-support#177
In dependant modules there still will be the version that is provided by spring-boot-dependencies. This causes test failures with the exception:
`ExceptionInInitializerError: Exception java.lang.IllegalStateException: Failed to verify that image 'apache/kafka-native:3.8.0' is a compatible substitute for 'apache/kafka'. This generally means that you are trying to use an image that Testcontainers has not been designed to use.`
So I suggesting to revert this for now and waiting for the spring-boot-dependencies v3.4.0 release which will contain new version of testcontainers that supports this "apache/kafka-native:3.8.0"
=> Revert "FOLSPRINGS-165: kafka.KafkaContainer, apache/kafka-native:3.8.0"

NEWS.md, folio-spring-i18n/src/main/java/org/folio/spring/i18n/model/TranslationMap.java, folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/model/TranslationMapTest.java, pom.xml
This adds a series of convenience methods for i18n, particularly for providing custom locales and timezones. Locales are typically guessed by the request context, however, this is not always available (for example, in background tasks), so a failsafe is nice.
Additionally, there is currently no way to get a user's timezone based on headers, so we don't have a way for `folio-spring-i18n` to guess the user's timezone. As such, we are now also providing methods for custom timezones to be passed in (and, if none is provided, the system time will be used, as was the previous default).
It may be worthwhile to consider API calls to mod-configuration to get the tenant's locale settings in the future, but that is well outside the scope of this ticket.
The timezone part was a bit tricky, as `icu4j` …
=> [FOLSPRINGS-169] Additional i18n methods

folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java
There is a potential for concurrent modifications to `localeTranslations` within the `TranslationService` if multiple format requests are issued simultaneously and the cache is empty. This PR properly uses a `ConcurrentHashMap` and synchronizes the necessary methods.
=> [FOLSPRINGS-171] i18n Use concurrent maps and synchronized methods where necessary

folio-spring-base/src/main/java/org/folio/spring/utils/FolioExecutionContextUtils.java, folio-spring-base/src/test/java/org/folio/spring/utils/FolioExecutionContextUtilsTest.java
[FOLSPRINGS-174](https://folio-org.atlassian.net/browse/FOLSPRINGS-174) - x-okapi-tenant header duplication
Implement a case-insensitivity check for the x-okapi-tenant header to prevent duplication.
* Implemented FolioExecutionContextUtils to set up context for tenant
* Added unit test
=> FOLSPRINGS-174 - x-okapi-tenant header duplication

folio-spring-base/pom.xml, folio-spring-base/src/main/java/org/folio/spring/liquibase/FolioLiquibaseConfiguration.java, folio-spring-cql/pom.xml, pom.xml
Upgrade from Spring Boot 3.3 to Spring Boot 3.4 for Sunflower
US: [FOLSPRINGS-161](https://folio-org.atlassian.net/browse/FOLSPRINGS-161), [FOLSPRINGS-177](https://folio-org.atlassian.net/browse/FOLSPRINGS-177)
* upgrade to `spring-boot v3.4.0` and `spring-cloud-starter-openfeign v4.2.0`
* exclude `spring-boot-starter-logging` from `spring-boot-starter-data-jpa` to avoid different slf4j2 implementations
* adjust `FolioLiquibaseConfiguration` according to https://github.com/spring-projects/spring-boot/commit/fae3cd1ca55575c01df324de04391cddf7fb9cd6#diff-3690614f74b4c856a949f9746fd77a870c9d32fc90ade726e515780a17c65a2aR109
=> FOLSPRINGS-161: Spring Boot 3.4

folio-spring-system-user/src/main/java/org/folio/spring/config/OptionalSystemUserConfig.java, folio-spring-system-user/src/main/java/org/folio/spring/config/SystemUserConfig.java, folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java, folio-spring-system-user/src/test/java/org/folio/spring/config/SystemUserConfigTest.java
https://jenkins-aws.indexdata.com/job/folio-org/job/mod-roles-keycloak/job/master/180/consoleFull displayed an issue in tests where build failed if the system user was disabled, due to a lack of a `SystemUserService`. This is due to our `OptionalSystemUserConfig` which only provides the `systemUserService` bean iff the system user is enabled, however, #220 added it as a required bean for initialization of `PrepareSystemUserService`, a bean which is provided in all contexts.
This provides a fallback for this case, creating a `PrepareSystemUserService` with a missing `SystemUserService`, as it is not needed when there is no system user work to do.
I could have used an `ObjectProvider` or `Optional` directly in `PrepareSystemUserService` instead, however, I opted for the extra configuration …
=> [FOLSPRINGS-183] Fix initialization when system user is disabled

folio-spring-system-user/src/main/java/org/folio/spring/client/UsersClient.java, folio-spring-system-user/src/test/java/org/folio/spring/client/UsersClientTest.java
Resolve a bug occurring during platform build where the `POST /users` request is invalid
```
fatal: [10.36.1.8]: FAILED! => {"changed": false, "connection": "close", "content": "POST request for mod-entities-links-3.2.0-SNAPSHOT.316 /_/tenant failed with 500: {\"errors\":[{\"message\":\"[422 Unprocessable Entity] during [POST] to [http://users/] [UsersClient#createUser(User)]: [{\\\"errors\\\":[{\\\"message\\\":\\\"Unrecognized field \\\\\\\"extraProperties\\\\\\\" (class org.folio.rest.jaxrs.model.User), not marked as ignorable (19 known properties: \\\\\\\"barcode\\\\\\\", \\\\\\\"departments\\\\\\\", \\\\\\\"meta\\\\\\\", \\\\\\\"active\\\\\\\",... (697 bytes)]\",\"type\":\"UnprocessableEntity\",\"code\":\"unknown\",\"parameters\":[]}],\"total_records\":1}", "content_length": "522", …
```
=> [FOLSPRINGS-183] Fix user serialization

folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java
In the improvements to the system user library, a sanity check was added after the system user is created to ensure the system user actually works. This is done by attempting to login as the system user, failing the install if the system user does not work, to ensure we fail sooner and make it easier for implementers and developers to troubleshoot, rather than waiting for a later user-invoked action to result in failure.
However, our integration test (Karate) environments are setup in such a way that, during regular module's install, `mod-authtoken` is not available. `authtoken` is declared as an optional dependency of `login`, so this is technically allowed, however, it makes our attempted login fail. Until this is fixed, we should not fail the module upgrade as described above. 
Turn …
=> [FOLSPRING-183] [system-user] Make login failure during tenant install into a soft failure

folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java
Parts of `authSystemUser` may already catch the `FeignException`, wrapping it with a custom one — to be safe, we will catch any runtime exceptions here.
=> [FOLSPRINGS-183] [system-user] Catch broader exception in sanity check

folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java
This soft failure was only temporary while we waited for Karate tests to get updated. This has now been resolved, so we can restore this check into it's original form.
This reverts #228 and #229
=> Revert "[FOLSPRING-183] [system-user] Make login failure during tenant install into a soft failure"

NEWS.md, README.md, folio-spring-base/src/main/java/org/folio/spring/liquibase/FolioSpringLiquibase.java, folio-spring-cql/src/main/java/org/folio/spring/cql/Cql2JpaCriteria.java, folio-spring-cql/src/main/java/org/folio/spring/cql/IgnoreAccents.java, folio-spring-cql/src/main/java/org/folio/spring/cql/IgnoreCase.java, folio-spring-cql/src/main/java/org/folio/spring/cql/JpaCqlRepository.java, folio-spring-cql/src/main/java/org/folio/spring/cql/JpaCqlRepositoryImpl.java, folio-spring-cql/src/main/java/org/folio/spring/cql/RespectAccents.java, folio-spring-cql/src/main/java/org/folio/spring/cql/RespectCase.java, folio-spring-cql/src/test/java/org/folio/spring/cql/JpaCqlModifiersIT.java, folio-spring-cql/src/test/java/org/folio/spring/cql/JpaCqlRepositoryIT.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/Language.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/LanguageRespectAccents.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/LanguageRespectCase.java, folio-spring-cql/src/test/java/org/folio/spring/cql/domain/LanguageRespectCaseRespectAccents.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/LanguageRepository.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/LanguageRespectAccentsRepository.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/LanguageRespectCaseRepository.java, folio-spring-cql/src/test/java/org/folio/spring/cql/repo/LanguageRespectCaseRespectAccentsRepository.java, folio-spring-cql/src/test/resources/sql/jpa-cql-general-it-schema.sql, folio-spring-cql/src/test/resources/sql/jpa-cql-lang-ignore-case-test-data.sql
[FOLSPRINGS-185](https://folio-org.atlassian.net/browse/FOLSPRINGS-185)
This implements case ignoring (= case insensitive) and accents ignoring CQL queries for String fields as default for Sunflower.
The back-port to Ramsons and Sunflower will have enable this only if a flag is set so that other modules won't be affected by this breaking change. This flag will be added for the Ramsons and Sunflower back-port only.
=> FOLSPRINGS-185 Implement case insensitive accents ignoring CQL queries

NEWS.md, folio-spring-base/src/main/resources/log4j2-json.properties, folio-spring-base/src/main/resources/log4j2.properties, folio-spring-base/src/test/resources/log4j2-test.xml, folio-spring-cql/src/test/resources/log4j2-test.xml, folio-spring-i18n/src/test/resources/log4j2-test.xml, folio-spring-system-user/src/test/resources/log4j2-test.xml, pom.xml
The use of the `packages` field in the Log4j configuration is deprecated. This task aims to remove the usage of this deprecated field and instead register the plugin using the Log4j annotation processor. This ensures forward compatibility with future Log4j versions and aligns with current best practices for plugin registration.
https://logging.apache.org/log4j/2.x/manual/plugins.html#plugin-registry)
=> FOLSPRINGS-197 Migrate Log4j plugin registration to annotation processor

NEWS.md, folio-spring-i18n/src/main/java/org/folio/spring/i18n/config/TranslationConfiguration.java, folio-spring-i18n/src/main/java/org/folio/spring/i18n/service/TranslationService.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/service/TranslationServiceGetFilesTest.java, folio-spring-i18n/src/test/java/org/folio/spring/i18n/service/TranslationServiceResolutionTest.java, folio-spring-i18n/src/test/resources/test-translations/test-combined/mod-bar/test.json, folio-spring-i18n/src/test/resources/test-translations/test-combined/mod-baz/test.json, folio-spring-i18n/src/test/resources/test-translations/test-multiple/mod-bar/en.json
Currently `TranslationConfiguration` only supports a single `translationDirectory`; this change allows use of a `List` of `translationDirectories`. Some use cases require searching more than one translations directory (such as `mod-fqm-manager` with [UXPROD-5169](https://folio-org.atlassian.net/browse/UXPROD-5169)).
=> [FOLSPRINGS-198] [i18n] Support multiple translation search directories

NEWS.md, README.md, folio-spring-base/src/main/java/org/folio/spring/exception/FolioContextExecutionException.java, folio-spring-base/src/main/java/org/folio/spring/scope/FolioExecutionContextService.java, folio-spring-base/src/test/java/org/folio/spring/exception/FolioContextExecutionExceptionTest.java, folio-spring-base/src/test/java/org/folio/spring/scope/FolioExecutionContextServiceTest.java, folio-spring-system-user/README.md, folio-spring-system-user/pom.xml, folio-spring-system-user/src/main/java/org/folio/spring/client/AuthnClient.java, folio-spring-system-user/src/main/java/org/folio/spring/client/PermissionsClient.java, folio-spring-system-user/src/main/java/org/folio/spring/client/UsersClient.java, folio-spring-system-user/src/main/java/org/folio/spring/config/properties/FolioEnvironment.java, folio-spring-system-user/src/main/java/org/folio/spring/context/ExecutionContextBuilder.java, folio-spring-system-user/src/main/java/org/folio/spring/context/SystemUserExecutionContext.java, folio-spring-system-user/src/main/java/org/folio/spring/exception/SystemUserAuthorizationException.java, folio-spring-system-user/src/main/java/org/folio/spring/model/ResultList.java, folio-spring-system-user/src/main/java/org/folio/spring/model/SystemUser.java, folio-spring-system-user/src/main/java/org/folio/spring/model/UserToken.java, folio-spring-system-user/src/main/java/org/folio/spring/service/PrepareSystemUserService.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserProperties.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserScopedExecutionService.java, folio-spring-system-user/src/main/java/org/folio/spring/service/SystemUserService.java, folio-spring-system-user/src/main/java/org/folio/spring/utils/TokenUtils.java
The system-user submodule was implemented to support cross-module interaction in Okapi-based environments.
In an Eureka-based environment, there is another approach for cross-module interaction integrated into the platform.
This means the system-user submodule is not needed anymore.
The plan is to deprecate it in Trillium and remove it in the next release after Trillium
https://folio-org.atlassian.net/browse/FOLSPRINGS-201
=> chore(system-user): deprecate submodule
